import re

with open("src/App.jsx", "r") as f:
    text = f.read()

replacements = {
    "Web design, development and brand experience from a single source.": "Webdesign, Development und Brand Experience aus einer Hand.",
    "Web design that makes brands look bigger.": "Webdesign, das Marken größer wirken lässt.",
    "We design modern websites that not only look good, but build trust, guide users, and perform measurably.": "Wir gestalten moderne Webseiten, die nicht nur gut aussehen, sondern Vertrauen schaffen, Nutzer führen und messbar performen.",
    "Services — Design": "Leistungen — Gestaltung",
    "What we build": "Was wir bauen",
    "From complete brand identities to individual campaign pages — appearances that show attitude.": "Vom kompletten Markenauftritt bis zur einzelnen Kampagnenseite — Auftritte, die Haltung zeigen.",
    "Modern websites with strong visual appearance and clear user guidance.": "Moderne Websites mit starker visueller Präsenz und klarer Nutzerführung.",
    "Conversion-optimized pages for products, campaigns, and services.": "Conversion-optimierte Seiten für Produkte, Kampagnen und Dienstleistungen.",
    "Digital brand worlds with recognition value and high-quality aesthetics.": "Digitale Markenwelten mit Wiedererkennungswert und hochwertiger Ästhetik.",
    "Services — Implementation": "Leistungen — Umsetzung",
    "And how": "Und wie",
    "we build": "wir bauen",
    "Design is one half. The other is clean craftsmanship.": "Gestaltung ist die eine Hälfte. Die andere ist sauberes Handwerk.",
    "Structured interfaces, clear user guidance, and intuitive experiences.": "Strukturierte Interfaces, klare Nutzerführung und intuitive Erlebnisse.",
    "Clean, fast, and responsive implementation of modern websites.": "Saubere, schnelle und responsive Umsetzung moderner Websites.",
    "Optimization for speed, user behavior, and better conversion.": "Optimierung auf Geschwindigkeit, Nutzerverhalten und bessere Conversion.",
    "Work that <span className=\"display-italic\">works</span>": "Arbeiten, die <span className=\"display-italic\">wirken</span>",
    "Eight custom concept and app demos — all live and interactive in the browser.": "Acht eigene Konzept- und App-Demos — alle live und im Browser bedienbar.",
    "Concept Demo · Barber & Hairdresser": "Konzept-Demo · Barber & Friseur",
    "Masculine-editorial website for a premium barbershop — cinematic 3D hero, appointment-focused.": "Maskulin-editoriale Website für einen Premium-Barbershop — cinematischer 3D-Hero, terminfokussiert.",
    "View Demo": "Demo ansehen",
    "Concept Demo · Fine Dining": "Konzept-Demo · Fine Dining",
    "Atmospheric website for fine dining — moody menu storytelling, reservation-focused.": "Atmosphärische Website für gehobene Gastronomie — stimmungsvolles Menü-Storytelling, auf Reservierungen ausgelegt.",
    "Concept Demo · General Practice": "Konzept-Demo · Hausarztpraxis",
    "Calm, trustworthy website for a general practice — clear structure, accessible, appointment-focused.": "Ruhige, vertrauensstarke Website für eine Hausarztpraxis — klare Struktur, barrierearm, terminfokussiert.",
    "More demos on{/* */}": "Weitere Demos auf{/* */}",
    "From a single": "Aus einer",
    "Hand": "Hand",
    "Scale & Form is a web design and web development studio for modern brands, companies, and digital products — websites, landing pages, brand experiences, and UI/UX systems with a focus on trust, user guidance, and conversion.": "Scale & Form ist ein Webdesign- und Webentwicklungsstudio für moderne Marken, Unternehmen und digitale Produkte — Websites, Landingpages, Brand Experiences und UI/UX-Systeme mit Fokus auf Vertrauen, Nutzerführung und Conversion.",
    "Strategy, design, and technical implementation come from a single source — from the first sketch to launch.": "Strategie, Design und technische Umsetzung kommen bei uns aus einer Hand — von der ersten Skizze bis zum Launch.",
    "From Briefing": "Vom Briefing",
    "to Launch": "zum Launch",
    "Four steps every project goes through — with no surprises in between.": "Vier Schritte, die jedes Projekt durchläuft — ohne Überraschungen dazwischen.",
    "Analysis": "Analyse",
    "We understand the brand, target audience, market, and goals.": "Marke, Zielgruppe, Markt und Ziele.",
    "Concept": "Konzept",
    "We develop the structure, design direction, and user guidance.": "Struktur, Designrichtung, Nutzerführung.",
    "Design & Development": "Design & Entwicklung",
    "We design and build the website to be high-quality and responsive.": "Hochwertig und responsive gebaut.",
    "Launch & Optimization": "Launch & Optimierung",
    "We publish, test, and continue to optimize the site.": "Veröffentlichen, testen, nachschärfen.",
    "Clarity <span className=\"display-italic\">upfront</span>": "Klarheit <span className=\"display-italic\">vorab</span>",
    "In Detail": "Im Detail",
    "How is such a presence created?": "Wie entsteht so ein Auftritt?",
    "What runs technically in the background?": "Was läuft technisch im Hintergrund?",
    "Does it work on every device?": "Funktioniert das auf jedem Gerät?",
    "First the dramaturgy: which scene carries which message. Only then are design and code created. Camerawork, lighting, and typography are set like in a studio — digital, but with photographic ambition.": "Zuerst die Dramaturgie: welche Szene welche Aussage trägt. Erst danach entstehen Design und Code. Kameraführung, Licht und Typografie werden wie im Studio gesetzt — digital, aber mit fotografischem Anspruch.",
    "Real-time 3D directly in the browser via WebGL. No video, no plugin. Material, reflection, and shadows react live to camera and light, and the entire image chain is built for a strict frame budget.": "Echtzeit-3D direkt im Browser über WebGL. Kein Video, kein Plugin. Material, Reflexion und Schatten reagieren live auf Kamera und Licht, und die gesamte Bildkette ist auf ein festes Frame-Budget hin gebaut.",
    "The composition is rethought for each device rather than just scaled down. On desktop the full spatial arrangement, on the phone a flat, calm version with the same content. Those who have reduced motion get the static variant.": "Die Komposition wird pro Gerät neu gedacht statt nur verkleinert. Auf dem Desktop die volle räumliche Anordnung, auf dem Telefon eine flache, ruhige Fassung mit denselben Inhalten. Wer Bewegung reduziert hat, bekommt die statische Variante.",
    "The System": "Das System",
    "How a presence<span className=\"block\">is put together</span>": "Wie ein Auftritt<span className=\"block\">zusammengesetzt ist</span>",
    "Not a gut feeling, but a system: delivery, weighting, process, and craftsmanship interlock.": "Kein Bauchgefühl, sondern ein System: Auslieferung, Gewichtung, Ablauf und Handwerk greifen ineinander.",
    "Reach": "Reichweite",
    "Delivered worldwide": "Weltweit ausgeliefert",
    "Every page lives at the edges of the network — close to the people who open them.": "Jede Seite liegt an den Rändern des Netzes — nah an den Menschen, die sie öffnen.",
    "Regionen": "Regionen",
    "Weighting": "Gewichtung",
    "Skill Profile": "Fähigkeitsprofil",
    "Where the weight lies in a project — it shifts depending on the type.": "Wo in einem Projekt das Gewicht liegt — je nach Typ verschiebt es sich.",
    "Weighting 0-100 per project type — profile, not measured values.": "Gewichtung 0–100 je Projekttyp — Profil, keine Messwerte.",
    "Process": "Ablauf",
    "From briefing to launch": "Vom Briefing zum Launch",
    "Brand, target audience, market, and goals.": "Marke, Zielgruppe, Markt und Ziele.",
    "Structure, design direction, user guidance.": "Struktur, Designrichtung, Nutzerführung.",
    "Built high-quality and responsive.": "Hochwertig und responsive gebaut.",
    "Publish, test, refine.": "Veröffentlichen, testen, nachschärfen.",
    "Pipeline": "Pipeline",
    "What happens before launch": "Was vor dem Launch passiert",
    "Scene calibrated": "Szene kalibriert",
    "Camera, lighting, and material per section": "Kamera, Licht und Material pro Abschnitt",
    "Framerate checked": "Bildrate geprüft",
    "Frame budget on desktop and mobile": "Frame-Budget auf Desktop und Mobile",
    "Contrast checked": "Kontrast geprüft",
    "Text readability over moving background": "Textlesbarkeit über bewegtem Hintergrund",
    "Attitude": "Haltung",
    "What we stand by": "Woran wir uns halten",
    "Real-time": "Echtzeit",
    "Every image is calculated in the moment": "Jedes Bild wird im Moment berechnet",
    "One piece": "Aus einem Guss",
    "Concept, design, and technology from a single source": "Konzept, Design und Technik aus einer Hand",
    "Measured": "Gemessen",
    "Load time and frame rate checked, not guessed": "Ladezeit und Bildrate geprüft, nicht geschätzt",
    "Activity": "Aktivität",
    "A Year, <span className=\"display-italic\">Day by Day</span>": "Ein Jahr, <span className=\"display-italic\">Tag für Tag</span>",
    "Each cell is a workday. Dense weeks are build phases, quiet weeks are coordination and testing.": "Jede Zelle ist ein Arbeitstag. Dichte Wochen sind Aufbauphasen, ruhige Wochen sind Abstimmung und Test.",
    "Project Inquiry": "Projektanfrage",
    "Ready to take the <span className=\"display-italic\">leap</span>": "Bereit, den Sprung<span className=\"display-italic\">zu machen</span>",
    "Tell us about your project in a few questions. We will get back to you personally — with an honest assessment, not a standard offer.": "Erzählen Sie uns in wenigen Fragen von Ihrem Vorhaben. Wir melden uns persönlich — mit einer ehrlichen Einschätzung, nicht mit einem Standardangebot.",
    "Start Project Inquiry": "Projekt anfragen",
    "Takes about 60 seconds.": "Dauert etwa 60 Sekunden.",
    "Modern websites, landing pages, and digital brand experiences from a single source.": "Moderne Websites, Landingpages und digitale Markenauftritte aus einer Hand.",
    "All rights reserved.": "Alle Rechte vorbehalten.",
    "In Numbers": "In Zahlen",
    "What has measurably remained from the work of the last projects.": "Was aus der Arbeit der letzten Projekte messbar geblieben ist."
}

for eng, ger in replacements.items():
    text = text.replace(eng, ger)

with open("src/App.jsx", "w") as f:
    f.write(text)
print("Done reverting text to German in App.jsx")
